### no sha256
POST http://localhost:9308/search
Content-Type: application/json

{
"table":"files",
"query": {
    "bool": {
      "must": [
        {
          "equals": {
            "sha256": ""
          }
        }
      ]
}
}
}

### no tc
POST http://localhost:9308/search
Content-Type: application/json

{
"table":"files",
  "join": [
    {
      "type": "left",
      "table": "tc",
      "on": [
        {
          "left": {
            "table": "tc",
            "field": "id"
          },
          "operator": "eq",
          "right": {
            "table": "files",
            "field": "id"
          }
        }
      ]
    }
  ],
"query": {
    "bool": {
      "must": [
        {
          "equals": {
            "tc.id": 0
          }
        }
      ],
      "must_not": [
        {
          "equals": {
            "tc.id": 0
          }
        }
      ]
}
},
  "sort": ["id"]
}

###